package com.jbit.dao;

import com.jbit.entity.BackendUser;

public interface BackendUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user
     *
     * @mbggenerated
     */
    int insert(BackendUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user
     *
     * @mbggenerated
     */
    int insertSelective(BackendUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user
     *
     * @mbggenerated
     */
    BackendUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BackendUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backend_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BackendUser record);
}