package com.jbit.dao;

import com.jbit.entity.DevUser;
import org.apache.ibatis.annotations.Param;

public interface DevUserMapper {
    DevUser findloginUser(@Param("devcode") String devcode, @Param("devpassword") String devpassword);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_user
     *
     * @mbggenerated
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_user
     *
     * @mbggenerated
     */
    int insert(DevUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_user
     *
     * @mbggenerated
     */
    int insertSelective(DevUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_user
     *
     * @mbggenerated
     */
    DevUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DevUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dev_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DevUser record);
}